export const projects = [
  {
    id: "adigami",
    name: "Adigami",
    naam: "",
    breif:
      "Jaipan, a name born of Jaipur and Japan, signifies the meeting of two distant worlds. It is a studio where cultures converge, folding intricacy and simplicity into one soul, and where the spirit of origami becomes architecture itself.",
    description: [
      "Jaipan is born at the intersection of two cultures: Jaipur, a city of colour, craft, and intricacy, and Japan, a land of origami, minimalism, and meditation. Conceived as a studio for an origami artist, it becomes a spatial dialogue where maximalism and minimalism, detail and restraint, find balance.",
      "The challenge lay in merging two aesthetics so different, yet so alike in spirit. Shared traditions - low floor seating, timber as a grounding material, and spaces that invite stillness - became bridges. Tatami mats articulate the flooring, ceilings glow with deep Jaipur reds reminiscent of frescoes, while light-toned woodwork recalls Japanese interiors. Block-printed cushions embed Jaipur’s textile craft within Japan’s simplicity.",
      "Origami flows through the space not as display, but as architecture. Walls, consoles, shutters, and luminaires embody folded forms, blurring the line between art and structure. Shoji-inspired windows with translucent washi diffuse daylight, while a wall of crumpled paper embraces imperfection - celebrating folds, iterations, and the poetry of process.",
      "The spatial sequence unfolds in three movements: a meditative folding zone, a collaborative workspace anchored by a communal table, and a private retreat for the artist. Together, they mirror the act of origami - precise, layered, and transformative.",
    ],
    foot: "Jaipan is more than a studio; it is an architectural fold - Jaipur and Japan, intricacy and minimalism, merging into one continuous gesture.",
    location: "",
    cover: "/projects/adigami/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/adigami/1.jpg",
      "/projects/adigami/2.jpg",
      "/projects/adigami/3.jpg",
      "/projects/adigami/4.jpg",
      "/projects/adigami/5.jpg",
      "/projects/adigami/6.jpg",
      "/projects/adigami/7.jpg",
      "/projects/adigami/8.jpg",
      "/projects/adigami/9.jpg",
      "/projects/adigami/10.jpg",
      "/projects/adigami/11.jpg",
      "/projects/adigami/12.jpg",
      "/projects/adigami/13.jpg",
      "/projects/adigami/14.jpg",
      "/projects/adigami/15.jpg",
    ],
  },
  {
    id: "aikyam",
    name: "Aikyam",
    naam: "",
    breif:
      "Aikyam - meaning oneness - captures the quiet harmony where soul, science, and spatial clarity come together. It is where every architectural choice, from structure to surface, belongs to a larger ecosystem - unified, grounded, and intentional.",
    description: [
      "AIKYAM is an inward-looking residence designed for a retired army couple - seasoned by movement, now longing for stillness. After a life of travel, change, and social engagement, they sought a space that turns away from the outside and returns to the self. The result is a home that breathes from its core - a central courtyard that anchors not just the plan, but the philosophy of living.",
      "Unlike outward-facing homes with terraces and balconies seeking the world, AIKYAM gathers all energy inward. This isn't just aesthetic - it's scientific and spatially conscious. A precise interplay of horizontal and vertical circulation ensures consistent air flow throughout, naturally ventilating the home. Strategic cutouts wrapped in terracotta jaalis invite wind while filtering light, keeping dust and heat at bay. The absence of exhaust systems isn't oversight - it's design. Here, wind flows with pressure, freshness remains constant, and temperature is passively regulated. The architecture becomes an organism.",
      "Every material was chosen for character and climate. Kota stone offers thermal comfort underfoot, Rohida wood and brass accents lend depth and memory. The spatial restraint allows these materials to shine without noise. Dark wood furniture, Tanjore paintings, and low gardens whisper of southern warmth and tactile intimacy. The house doesn't shout luxury - it reveals it, through timeless textures and a gentle choreography of breeze, light, and shadow.",
    ],
    foot: "In AIKYAM, the couple's story is the context. The architecture only listens - and then, lovingly responds. A home not just built, but felt. ",
    location: "",
    cover: "/projects/aikyam/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/aikyam/1.jpg",
      "/projects/aikyam/2.jpg",
      "/projects/aikyam/3.jpg",
      "/projects/aikyam/4.jpg",
      "/projects/aikyam/5.jpg",
      "/projects/aikyam/6.jpg",
      "/projects/aikyam/7.jpg",
      "/projects/aikyam/8.jpg",
      "/projects/aikyam/9.jpg",
      "/projects/aikyam/10.jpg",
      "/projects/aikyam/11.jpg",
      "/projects/aikyam/12.jpg",
      "/projects/aikyam/13.jpg",
      "/projects/aikyam/14.jpg",
      "/projects/aikyam/15.jpg",
    ],
  },
  {
    id: "buffer",
    name: "Buffer",
    naam: "",
    breif:
      "Samanvay signifies balance, coming together, a quiet alignment of many energies into one rhythm. Conceived as a coworking space, the project reimagines work not as a rigid routine, but as a more human experience - where collaboration, calmness, individuality, and community coexist in harmony.",
    description: [
      "The palette is grounded in earthy reds, warm neutrals, natural wood, and woven cane, creating an atmosphere that feels calm, welcoming, and deeply rooted. Custom-designed furniture with sculptural wooden forms, handcrafted details, and cane weaving introduces a tactile richness, while carefully placed indoor greens soften the interiors and strengthen the connection with nature.",
      "Natural light becomes an active design element, casting shadows across textured walls, fluted surfaces, and handcrafted furniture throughout the day. Open meeting areas, collaborative tables, intimate work pods, reading corners, and informal seating zones encourage different modes of working - whether focused, collaborative, or reflective.",
      "Every detail, from the vintage accents and handcrafted décor to the material choices and spatial planning, contributes to a narrative of balance. The result is a workspace that feels less like an office and more like a living, breathing environment where ideas can gather, conversations can unfold, and creativity can thrive.",
    ],
    foot: "Samanvay is an exploration of how thoughtful design can bring together people, craft, culture, and work - creating a space that feels both purposeful and profoundly human.",
    location: "",
    cover: "/projects/buffer/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/buffer/1.jpg",
      "/projects/buffer/2.jpg",
      "/projects/buffer/3.jpg",
      "/projects/buffer/4.jpg",
      "/projects/buffer/5.jpg",
      "/projects/buffer/6.jpg",
      "/projects/buffer/7.jpg",
      "/projects/buffer/8.jpg",
      "/projects/buffer/9.jpg",
      "/projects/buffer/10.jpg",
      "/projects/buffer/11.jpg",
      "/projects/buffer/12.jpg",
      "/projects/buffer/13.jpg",
      "/projects/buffer/14.jpg",
      "/projects/buffer/15.jpg",
    ],
  },
  {
    id: "casa-v2",
    name: "Casa-v2",
    naam: "",
    breif: "",
    description: "",
    location: "",
    cover: "/projects/casa-v2/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/casa-v2/1.jpg",
      "/projects/casa-v2/2.jpg",
      "/projects/casa-v2/3.jpg",
      "/projects/casa-v2/4.jpg",
      "/projects/casa-v2/5.jpg",
      "/projects/casa-v2/6.jpg",
      "/projects/casa-v2/7.jpg",
      "/projects/casa-v2/8.jpg",
      "/projects/casa-v2/9.jpg",
      "/projects/casa-v2/10.jpg",
      "/projects/casa-v2/11.jpg",
      "/projects/casa-v2/12.jpg",
      "/projects/casa-v2/13.jpg",
      "/projects/casa-v2/14.jpg",
      "/projects/casa-v2/15.jpg",
    ],
  },
  {
    id: "chaisa",
    name: "Chaisa",
    naam: "",
    breif:
      "Darpan, meaning mirror, speaks of seeing and being seen, of holding an image yet transforming it. This project mirrors Jaipur's spirit - its heritage, its contrasts, its quiet eccentricities - while offering back a new reflection. It is not imitation, but resonance; not a copy, but a conscious echo of the city it belongs to.",
    description: [
      "Situated on Chaura Rasta - a street that holds the memory of eras from Mughal grandeur to British imprints and Art Deco modernity - the project becomes an echo of the city's layered character.",
      "The building was unconventional in today's context yet entirely authentic to its own time: narrow staircases with tall risers, small ten-inch windows, low ceilings, modest openings. Rather than erase these peculiarities, the design preserves them - retaining their honesty as reminders of how Jaipur once lived. Wooden brackets sit humbly beneath beams, walls are limewashed in the city's tradition, and every gate, knob, and niche resonates with the architecture's inherent voice.",
      "Yet within this modest frame, a bold move emerges: a playful contrast of green flooring against Jaipur's pink, a gesture that reinterprets heritage rather than replicating it. Terracotta jaalis breathe into the façade, merging with the UNESCO streetscape while subtly modernising its presence.",
      "Even the staircase becomes part of the philosophy - its steep risers designed not only for defense in the past but now as an intentional pause. A moment of consciousness before leaving the chaos of the street and entering a calmer, more reflective space.",
    ],
    foot: "Darpan is thus both mirror and mediator - bridging past and present, modesty and boldness, heritage and play - capturing Jaipur's spirit in every step, window, and wall.",
    location: "",
    cover: "/projects/chaisa/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/chaisa/1.jpg",
      "/projects/chaisa/2.jpg",
      "/projects/chaisa/3.jpg",
      "/projects/chaisa/4.jpg",
      "/projects/chaisa/5.jpg",
      "/projects/chaisa/6.jpg",
      "/projects/chaisa/7.jpg",
      "/projects/chaisa/8.jpg",
      "/projects/chaisa/9.jpg",
      "/projects/chaisa/10.jpg",
      "/projects/chaisa/11.jpg",
      "/projects/chaisa/12.jpg",
      "/projects/chaisa/13.jpg",
      "/projects/chaisa/14.jpg",
      "/projects/chaisa/15.jpg",
    ],
  },
  {
    id: "goa",
    name: "Goa",
    naam: "",
    breif:
      "Spandan means a pulse, a vibration, a quiet movement that signifies life. The concept emerged from the meeting of two forces - geometry and nature - where forms respond to climate, land, and emotion rather than rigid rules. Spandan is about flow: of wind, light, water, and human experience, shaped into architecture that feels alive rather than imposed.",
    description: [
      "Located along the untouched coastline of Redi Beach, Maharashtra, Spandan began with deep observation. Before design took form, the site was studied - its sun path, humidity, wind direction, rainfall patterns, and terrain. This understanding shaped every architectural decision, allowing the structure to belong to its environment rather than dominate it.",
      "The cottages are defined by polygonal geometries that create structural dynamism while remaining gentle against the seaside landscape. Instead of conventional sloping roofs used in heavy-rainfall regions, the design breaks precedent with curved, bowl-like terraces, subtly slanted for efficient drainage and rainwater harvesting. This rule-breaking move allowed clean, continuous ceilings while responding intelligently to climate.",
      "Interior experiences were designed to echo the first moment of standing on the site - where white sand meets blue ocean with no visual interruption. Inspired by Rajasthan's havelis, sleeping areas were elevated on plinths, with beds suspended and framed by ceiling cut-outs. The result is a sensory rhythm: waking up to the sea, falling asleep under the stars.",
      "Local materials and construction practices were embraced, particularly laterite stone native to the Western Ghats, grounding the project in its vernacular context. Despite Goa's popular tourist image, Spandan is rooted in the quietness of a village - peaceful, unhurried, and deeply connected to its surroundings. Playful geometry was introduced gently, balancing calm with character across ceilings, terraces, and spatial transitions.",
    ],
    foot: "More than a resort, Spandan represents a personal and professional evolution - where new climates, cultures, materials, and ways of living came together. It stands as a reminder that architecture is not just built on land, but shaped by listening to it.",
    location: "",
    cover: "/projects/goa/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/goa/1.jpg",
      "/projects/goa/2.jpg",
      "/projects/goa/3.jpg",
      "/projects/goa/4.jpg",
      "/projects/goa/5.jpg",
      "/projects/goa/6.jpg",
      "/projects/goa/7.jpg",
    ],
  },
  {
    id: "oat",
    name: "Oat",
    naam: "",
    breif:
      "Oat - drawn from the Hindi word for veil or ghoonghat - embodies the idea of shelter, modesty, and quiet strength. In this residence, Oat becomes more than a name - it becomes a lens through which space, light, and privacy are reimagined. The architectural screen is not just a visual motif; it is a philosophical gesture, balancing protection and permeability in a dense urban setting.",
    description: [
      "The residence reimagines urban living through the lens of shelter, modesty, and quiet strength. Situated on a compact site flanked by buildings on three sides and a bustling street in front, this residence filters its surroundings with precision rather than shutting them out.",
      "At its core lies a light-filled courtyard - a passive yet powerful design move that anchors the home, bringing in air, light, and a sense of openness. The distinctive jali façade acts as a contemporary veil: offering privacy, softening sunlight, and eliminating the need for curtains, while allowing the house to breathe and glow.",
      "The material palette is earthy and intentional - terracotta floors, cane accents, and greenery lend warmth and tactility. Every corner serves a purpose, from serene voids that frame the sky to social spaces that gather life.",
    ],
    foot: "Oat is not just a residence; it's an architectural response to urban density - quiet, porous, and poetic in its restraint",
    location: "",
    cover: "/projects/oat/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/oat/1.jpg",
      "/projects/oat/2.jpg",
      "/projects/oat/3.jpg",
      "/projects/oat/4.jpg",
      "/projects/oat/5.jpg",
      "/projects/oat/6.jpg",
      "/projects/oat/7.jpg",
      "/projects/oat/8.jpg",
      "/projects/oat/9.jpg",
      "/projects/oat/10.jpg",
      "/projects/oat/11.jpg",
      "/projects/oat/12.jpg",
      "/projects/oat/13.jpg",
      "/projects/oat/14.jpg",
      "/projects/oat/15.jpg",
    ],
  },
  {
    id: "ranthambore",
    name: "Ranthambore",
    naam: "",
    breif: "",
    description: "",
    location: "",
    cover: "/projects/ranthambore/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/ranthambore/1.jpg",
      "/projects/ranthambore/2.jpg",
      "/projects/ranthambore/3.jpg",
      "/projects/ranthambore/4.jpg",
      "/projects/ranthambore/5.jpg",
      "/projects/ranthambore/6.jpg",
      "/projects/ranthambore/7.jpg",
      "/projects/ranthambore/8.jpg",
      "/projects/ranthambore/9.jpg",
      "/projects/ranthambore/10.jpg",
      "/projects/ranthambore/11.jpg",
      "/projects/ranthambore/12.jpg",
      "/projects/ranthambore/13.jpg",
      "/projects/ranthambore/14.jpg",
      "/projects/ranthambore/15.jpg",
    ],
  },
  {
    id: "surbhi-farm",
    name: "Surbhi Farm",
    naam: "",
    breif: "",
    description: "",
    location: "",
    cover: "/projects/surbhi-farm/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/surbhi-farm/1.jpg",
      "/projects/surbhi-farm/2.jpg",
      "/projects/surbhi-farm/3.jpg",
      "/projects/surbhi-farm/4.jpg",
      "/projects/surbhi-farm/5.jpg",
      "/projects/surbhi-farm/6.jpg",
      "/projects/surbhi-farm/7.jpg",
      "/projects/surbhi-farm/8.jpg",
      "/projects/surbhi-farm/9.jpg",
      "/projects/surbhi-farm/10.jpg",
      "/projects/surbhi-farm/11.jpg",
      "/projects/surbhi-farm/12.jpg",
      "/projects/surbhi-farm/13.jpg",
      "/projects/surbhi-farm/14.jpg",
      "/projects/surbhi-farm/15.jpg",
    ],
  },
  {
    id: "tatvam-vas",
    name: "Tatvam Vas",
    naam: "",
    breif:
      "Tatvam Vas - drawn from the Sanskrit phrase “You are that” - is a quiet assertion of oneness with nature. It is a retreat rooted in stillness, where architecture doesn't impose, but listens — to the land, the light, and the air.",
    description: [
      "Set amidst the arid landscapes of Achrol, Rajasthan, Tatvam Vas is a 6,500 sq ft residence conceived as a living expression of sustainable design. Built on a site once slated for sale, it instead became a canvas for a regenerative home - one that treads lightly yet lives fully.",
      "Constructed with 40% less cement, and entirely free of plaster or tiles, the home uses hollow terracotta bricks to self-regulate temperature - remaining up to 8°C cooler in peak summers. Locally sourced materials - Sheesham, Babool, Kota stone, upcycled timber - ground the structure in its vernacular, while hand-crafted elements like brass joints and indigo-dyed mortar replace industrial finishes with natural nuance.",
      "The spatial design invites natural light into every room, and employs Bernoulli's principle to create gentle cross-ventilation through corridors, jaali work, and opposing windows. Water is harvested and recycled; waste is composted; air flows freely within and around the built form.Every decision - from the blue-hued pool to bamboo-clad interiors - reflects restraint, responsibility, and reverence.",
    ],
    foot: "At Tatvam Vas, sustainability isn't applied - it is inherent. A home that lives in dialogue with its environment, and with those who dwell within it.",
    location: "",
    cover: "/projects/tatvam-vas/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/tatvam-vas/1.jpg",
      "/projects/tatvam-vas/2.jpg",
      "/projects/tatvam-vas/3.jpg",
      "/projects/tatvam-vas/4.jpg",
      "/projects/tatvam-vas/5.jpg",
      "/projects/tatvam-vas/6.jpg",
      "/projects/tatvam-vas/7.jpg",
      "/projects/tatvam-vas/8.jpg",
      "/projects/tatvam-vas/9.jpg",
      "/projects/tatvam-vas/10.jpg",
      "/projects/tatvam-vas/11.jpg",
      "/projects/tatvam-vas/12.jpg",
      "/projects/tatvam-vas/13.jpg",
      "/projects/tatvam-vas/14.jpg",
      "/projects/tatvam-vas/15.jpg",
    ],
  },
  {
    id: "toto",
    name: "Toto",
    naam: "",
    breif: "",
    description: "",
    location: "",
    cover: "/projects/toto/1.jpg",
    area: "",
    ongoing: true,
    date: "",
    extra: "",
    images: [
      "/projects/toto/1.jpg",
      "/projects/toto/2.jpg",
      "/projects/toto/3.jpg",
      "/projects/toto/4.jpg",
      "/projects/toto/5.jpg",
      "/projects/toto/6.jpg",
      "/projects/toto/7.jpg",
      "/projects/toto/8.jpg",
      "/projects/toto/9.jpg",
      "/projects/toto/10.jpg",
      "/projects/toto/11.jpg",
      "/projects/toto/12.jpg",
      "/projects/toto/13.jpg",
      "/projects/toto/14.jpg",
      "/projects/toto/15.jpg",
    ],
  },
];
